### ISSUE TITLE
Ribbon not working for VertexIntrinsicVectorQuantity

### ISSUE THREAD

**Issue by dcoeurjo** [nmwsharp/polyscope#39] opened 2019-12-07 17:04 UTC
It looks like the ribbon shader has been disabled.. Checking/unchecking the "ribbon" checkbox in the interface does nothing (vectors are still displayed with the "arrow" geometry).

**Comment by nmwsharp** [comment] 2019-12-09 15:15
Hmm, seems to be working on my end.

![Screenshot from 2019-12-09 10-12-41](https://user-images.githubusercontent.com/12726725/70447378-99f54680-1a6c-11ea-921f-ca22f928d6f6.png)

Perhaps the preset width values is making it invisibly small or something? Can you give any more details?

**Comment by dcoeurjo** [comment] 2019-12-10 07:10
Mmm strange... Let me set up a clean example. 
Thx

**Comment by nmwsharp** [comment] 2020-01-24 22:38
Closing old issue. Feel free to reopen if it reappears!

**Comment by dcoeurjo** [comment] 2020-01-25 12:19
Sorry @nmwsharp , I was a bit swamped by a seasonal deadline ;)
I still have the bug, here you have a more precise but report:

Starting from the GC template and this simple code (the vector field is a cut/paste from the tuto, lines 90-100): https://gist.github.com/dcoeurjo/9370dc6872c234b4a83c3657cc64b7de

On macOS Catalina (MBPro 13"), `[polyscope] Loaded openGL version: 4.1 INTEL-14.4.14`, the vector field is fine but the Ribbon is not working (no error messages): 



![ezgif-2-1716873561ea](https://user-images.githubusercontent.com/700165/73120976-40da6700-3f75-11ea-8515-b4e1d1971579.gif)

**Comment by dcoeurjo** [comment] 2020-01-25 12:20
(looks like I cannot reopen the issue :/)

**Comment by dcoeurjo** [comment] 2020-01-25 12:33
(BTW why many direction field codes are commented in GC `direction_fields.cpp` ? (e.g. `computeSmoothestFaceDirectionField`)

**Comment by dcoeurjo** [comment] 2020-01-25 12:36
(maybe related to https://github.com/nmwsharp/geometry-central/issues/2)

**Comment by nmwsharp** [comment] 2020-01-25 20:29
No worries, I'm also getting back in to this after deadlines :) 

OK! I'll try to reproduce this, and otherwise see if I can add more error checks or something to diagnose the issue.

> why many direction field codes are commented in GC direction_fields.cpp

Yep, related to  nmwsharp/geometry-central#2 . The big release of geometry-central broke that code, and I never got around to updating it. They really shouldn't be in the header, since they're dead. I'll be putting a fair bit of time in to geometry-central over the next few weeks, so hopefully I can update those.

**Comment by nmwsharp** [comment] 2020-01-28 20:48
Ah, this was absolutely a bug. For vertex intrinsic vector quantities, the vector field was not being properly remapped to faces to perform tracing.

Fix is here: https://github.com/nmwsharp/polyscope/commit/dbaf927af6457a1f0ab502de14138e6499b9b8bd

That's in a feature branch which will get merged in to master as a new version within the next few days. Alternately, it should be safe to copy-paste that fix in to older code if you want it ASAP!

**Comment by dcoeurjo** [comment] 2020-01-29 08:52
👌 many thanks for the debugging and the fix 
(no rush on my side;))

**Comment by nmwsharp** [comment] 2020-01-29 18:23
Thanks for reporting!

Closing as fixed in dbaf927af6457a1f0ab502de14138e6499b9b8bd

**Closed by nmwsharp** 2020-01-29 18:23 UTC

**Comment by dcoeurjo** [comment] 2020-01-29 18:52
Thx!
